"""add created_at to audit_logs

Revision ID: 1c6b9bb848ad
Revises: 17988c186392
Create Date: 2026-01-18 19:12:14.436808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6b9bb848ad'
down_revision: Union[str, Sequence[str], None] = '17988c186392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('audit_logs', 'meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('audit_logs', 'time')
    op.add_column('notes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('transactions', 'risk')
    op.drop_column('transactions', 'shap_top')
    op.drop_column('transactions', 'label')
    op.drop_column('transactions', 'explanation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('label', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('shap_top', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('risk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('transactions', 'ts',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('notes', 'created_at')
    op.add_column('audit_logs', sa.Column('time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('audit_logs', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('audit_logs', 'created_at')
    # ### end Alembic commands ###
