"""add_created_at_and_update_schema

Revision ID: c04ceeabc68f
Revises: <KEEP_YOURS_FROM_GENERATED_FILE>
Create Date: 2026-01-26 09:23:24.912088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c04ceeabc68f'
down_revision: Union[str, Sequence[str], None] = '<KEEP_YOURS_FROM_GENERATED_FILE>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('audit_logs', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cases_assigned_to'), table_name='cases')
    op.add_column('notes', sa.Column('body', sa.String(length=2000), nullable=False))
    op.add_column('notes', sa.Column('author', sa.String(length=120), nullable=True))
    op.alter_column('notes', 'tx_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notes_case_id'), table_name='notes')
    op.create_foreign_key(None, 'notes', 'transactions', ['tx_id'], ['tx_id'], ondelete='CASCADE')
    op.drop_column('notes', 'content')
    op.drop_column('notes', 'updated_at')
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('transactions', 'tx_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('transactions', 'user',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('transactions', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'device',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'merchant',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('transactions', 'card_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'hour',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'explanation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transactions', 'shap_top',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'shap_top',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('transactions', 'explanation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'ts',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'hour',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'card_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'merchant',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('transactions', 'channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'device',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'user',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('transactions', 'tx_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('transactions', 'created_at')
    op.add_column('notes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_index(op.f('ix_notes_case_id'), 'notes', ['case_id'], unique=False)
    op.alter_column('notes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'tx_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('notes', 'author')
    op.drop_column('notes', 'body')
    op.create_index(op.f('ix_cases_assigned_to'), 'cases', ['assigned_to'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
